### ISSUE TITLE
trouble sourcing a 4053N

### ISSUE THREAD

**Issue by joem** [shaduzlabs/Synapse#2]
Hi there. I'm having a little trouble sourcing a 4053N... Not sure if I'm just being dense about it or not, but I can't seem to find the right chip. Will any 4053 do? Should it be CMOS? Is the N all that important? The only 4053N that Mouser has is SOIC. Cheers.

**Comment by shaduzlabs** [comment]
Hi Joe, I'm actually using a TI CD74HC4053E, which should be easy to source. Cheers, v.

**Comment by joem** [comment]
Ah, excellent. Thanks. I'm closing this "issue" then.
