### ISSUE TITLE
Troubleshooting CV outs

### ISSUE THREAD

**Issue by scottmetoyer** [shaduzlabs/Synapse#9]
The CV outs on my recent build only seem to output a constant 4 volts no matter what value I send to them (I'm using the test sketch to verify). The gates appear to be working ok.

All of my solder joints look ok, ICs are seated correctly. What are some things to check that would cause those symptoms?

**Comment by icnagy** [comment]
Try checking the voltages on the TL072’s input pins (2, 3 & 5, 6). If you have spares, try replacing the TL072 and/or the 4053N.

**Comment by scottmetoyer** [comment]
Embarrassing mistake! I was powering from USB when running the test sketch. I plugged in Eurorack power, ran the test, and everything worked as expected. Thanks!
